/*
 * Autogenerated by xmb2js.py at Wed Sep 27 16:28:15 2006 from
 *   ./js/locale/en/uistrings.xlb.
 */

/**
 * <p>displayed as a tab, as well as a header above a collection of image
 *   search results</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:7</p>
 */
var _MSG_SEARCHER_IMAGE = ('Image');

/**
 * <p>displayed as a tab, as well as a header above a collection of web
 *   search results</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:14</p>
 */
var _MSG_SEARCHER_WEB = ('Web');

/**
 * <p>displayed as a tab, as well as a header above a collection of blog
 *   search results</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:21</p>
 */
var _MSG_SEARCHER_BLOG = ('Blog');

/**
 * <p>displayed as a tab, as well as a header above a collection of video
 *   search results</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:28</p>
 */
var _MSG_SEARCHER_VIDEO = ('Video');

/**
 * <p>displayed as a tab, as well as a header above a collection of local
 *   search results</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:35</p>
 */
var _MSG_SEARCHER_LOCAL = ('Local');

/**
 * <p>displayed underneath a search result to invite a user to keep a given
 *   search result (this is one of several selectable alternatives)</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:42</p>
 */
var _MSG_SEARCHCONTROL_SAVE = ('save');

/**
 * <p>displayed underneath a search result to invite a user to keep a given
 *   search result (this is one of several selectable alternatives)</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:49</p>
 */
var _MSG_SEARCHCONTROL_KEEP = ('keep');

/**
 * <p>displayed underneath a search result to invite a user to keep a given
 *   search result (this is one of several selectable alternatives)</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:56</p>
 */
var _MSG_SEARCHCONTROL_INCLUDE = ('include');

/**
 * <p>displayed underneath a search result to invite a user to keep a given
 *   search result (this is one of several selectable alternatives)</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:63</p>
 */
var _MSG_SEARCHCONTROL_COPY = ('copy');

/**
 * <p>the text used to invite the user to close the configuration section for
 *   a given searcher</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:70</p>
 */
var _MSG_SEARCHCONTROL_CLOSE = ('close');

/**
 * <p>the text used to indicate the start of sponsored links</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:77</p>
 */
var _MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Sponsored Links');

/**
 * <p>the text used to invite the user to view more results. in partial
 *   expand mode, the control typically shows a single control, with this
 *   invite to view more</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:84</p>
 */
var _MSG_SEARCHCONTROL_SEE_MORE = ('see more...');

/**
 * <p>the text used to mark that a search result was selected by a user</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:91</p>
 */
var _MSG_SEARCHCONTROL_WATERMARK = ('clipped from Google');

/**
 * <p>This label is used above a text box, asking a user to specify a search
 *   location that local searches are performed relative to. A valid value
 *   would be a city, zip code, address, etc.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:98</p>
 */
var _MSG_SEARCHER_CONFIG_SET_LOCATION = ('Search location');

/**
 * <p>This label is used by a checkbox. Users can enable or disable address
 *   lookup, which is a feature of local search. With address lookup enabled,
 *   a search for NYC will return the center of New York, New York. With
 *   address search disabled, the same search will only find businesses that
 *   have something to do, or are located in NYC.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:105</p>
 */
var _MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Disable address lookup');

/**
 * <p>displayed as a tab, as well as a header above a collection of news
 *   search results. Identical to NewsFrontEnd msg News, ID=4</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:113</p>
 */
var _MSG_SEARCHER_NEWS = ('News');

/**
 * <p>The relative time associated with a story, in minutes, as in Washington
 *   Post - 13 minutes ago. Identical to NewsFrontEnd msg News, ID=23</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:120</p>
 * @param AGE_MINUTES_AGO
 */
function _MSG_MINUTES_AGO(AGE_MINUTES_AGO) {
  return ('' + AGE_MINUTES_AGO + ' minutes ago');
}

/**
 * <p>The relative time associated with a story that is 1 hour old, as in
 *   Washington Post - 1 hour ago. Identical to NewsFrontEnd msg News,
 *   ID=24</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:127</p>
 */
var _MSG_ONE_HOUR_AGO = ('1 hour ago');

/**
 * <p>The relative time associated with a story, in hours, as in Washington
 *   Post - 2 hours ago. Identical to NewsFrontEnd msg News, ID=25</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:134</p>
 * @param AGE_HOURS_AGO
 */
function _MSG_HOURS_AGO(AGE_HOURS_AGO) {
  return ('' + AGE_HOURS_AGO + ' hours ago');
}

/**
 * <p>Shown where there a a lot of related articles, as in all 13 related.
 *   Identical to NewsFrontEnd msg News, ID=175</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:141</p>
 * @param NUMBER
 */
function _MSG_NEWS_ALL_N_RELATED(NUMBER) {
  return ('all ' + NUMBER + ' related');
}

/**
 * <p>Shown when there are a lot of related articles, but when we do not have
 *   an accurate count, as in Related Articles. Identical to NewsFrontEnd msg
 *   News, ID=253</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:148</p>
 */
var _MSG_NEWS_RELATED = ('Related Articles');

/**
 * <p>A simple string users can place somewhere on their page to indicate
 *   that search results have been provided by Google.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:155</p>
 */
var _MSG_BRANDING_STRING = ('powered by Google');

/**
 * <p>An invitation to sort certain classes of results by date rather than by
 *   relevance. This is identical to NewsFrontEnd msg News, ID=148.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:162</p>
 */
var _MSG_SORT_BY_DATE = ('Sort by date');

/**
 * <p>The abbreviation for the month of January. This is identical to
 *   NewsFrontEnd msg News, ID=179.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:169</p>
 */
var _MSG_MONTH_ABBR_JAN = ('Jan');

/**
 * <p>The abbreviation for the month of February. This is identical to
 *   NewsFrontEnd msg News, ID=180.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:176</p>
 */
var _MSG_MONTH_ABBR_FEB = ('Feb');

/**
 * <p>The abbreviation for the month of March. This is identical to
 *   NewsFrontEnd msg News, ID=181.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:183</p>
 */
var _MSG_MONTH_ABBR_MAR = ('Mar');

/**
 * <p>The abbreviation for the month of April. This is identical to
 *   NewsFrontEnd msg News, ID=182.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:190</p>
 */
var _MSG_MONTH_ABBR_APR = ('Apr');

/**
 * <p>The abbreviation for the month of May. This is identical to
 *   NewsFrontEnd msg News, ID=183.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:197</p>
 */
var _MSG_MONTH_ABBR_MAY = ('May');

/**
 * <p>The abbreviation for the month of June. This is identical to
 *   NewsFrontEnd msg News, ID=184.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:204</p>
 */
var _MSG_MONTH_ABBR_JUN = ('Jun');

/**
 * <p>The abbreviation for the month of July. This is identical to
 *   NewsFrontEnd msg News, ID=185.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:211</p>
 */
var _MSG_MONTH_ABBR_JUL = ('Jul');

/**
 * <p>The abbreviation for the month of August. This is identical to
 *   NewsFrontEnd msg News, ID=186.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:218</p>
 */
var _MSG_MONTH_ABBR_AUG = ('Aug');

/**
 * <p>The abbreviation for the month of September. This is identical to
 *   NewsFrontEnd msg News, ID=187.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:225</p>
 */
var _MSG_MONTH_ABBR_SEP = ('Sep');

/**
 * <p>The abbreviation for the month of October. This is identical to
 *   NewsFrontEnd msg News, ID=188.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:232</p>
 */
var _MSG_MONTH_ABBR_OCT = ('Oct');

/**
 * <p>The abbreviation for the month of November. This is identical to
 *   NewsFrontEnd msg News, ID=189.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:239</p>
 */
var _MSG_MONTH_ABBR_NOV = ('Nov');

/**
 * <p>The abbreviation for the month of December. This is identical to
 *   NewsFrontEnd msg News, ID=190.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:246</p>
 */
var _MSG_MONTH_ABBR_DEC = ('Dec');

/**
 * <p>Displayed as a link in a local search result or in a maps info window
 *   bubble. Clicking produces walking or driving directions.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:253</p>
 */
var _MSG_DIRECTIONS = ('directions');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the icon used to clear all search results from the page.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:260</p>
 */
var _MSG_CLEAR_RESULTS = ('clear results');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the icon used to request a single search result.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:267</p>
 */
var _MSG_SHOW_ONE_RESULT = ('show one result');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the icon used to request more search results.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:274</p>
 */
var _MSG_SHOW_MORE_RESULTS = ('show more results');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the icon used to request all search results.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:281</p>
 */
var _MSG_SHOW_ALL_RESULTS = ('show all results');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the icon used to configure settings.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:288</p>
 */
var _MSG_SETTINGS = ('settings');

/**
 * <p>Used as tool tip text. The text appears when a user's mouse hovers over
 *   the search button</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:295</p>
 */
var _MSG_SEARCH = ('search');

/**
 * <p>Used as the text on the search button</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:302</p>
 */
var _MSG_SEARCH_UC = ('Search');

/**
 * <p>Used next to an image to indicate that the search control is powered by
 *   google. In this case, Google is an image.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:309</p>
 */
var _MSG_POWERED_BY = ('powered by');

/**
 * <p>Local search results sometimes require attribution. Something like
 *   Business listings provided by abc.com. This string is a part of that
 *   attribution</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:316</p>
 * @param LOCAL_RESULTS_PROVIDER
 */
function _MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {
  return ('Business listings provided by ' + LOCAL_RESULTS_PROVIDER + '');
}

/**
 * <p>displayed as a tab, as well as a header above a collection of book
 *   search results. this should match the standard tab for google.com book
 *   search</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:323</p>
 */
var _MSG_SEARCHER_BOOK = ('Book');

/**
 * <p>For book search, we tell people the page that contains that match as in
 *   - Page 4.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:330</p>
 * @param FOUND_ON_PAGE
 */
function _MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {
  return ('Page ' + FOUND_ON_PAGE + '');
}

/**
 * <p>For book search, we tell people how long the book is that contains
 *   their match as in: 343 pages.</p>
 * <p>Source: ./js/locale/en/uistrings.xlb:337</p>
 * @param PAGE_COUNT
 */
function _MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {
  return ('' + PAGE_COUNT + ' pages');
}
