var udsi=new Object;udsi["blank"]="&nbsp;";udsi["image"]=_MSG_SEARCHER_IMAGE;udsi["web"]=_MSG_SEARCHER_WEB;udsi["blog"]=_MSG_SEARCHER_BLOG;udsi["video"]=_MSG_SEARCHER_VIDEO;udsi["local"]=_MSG_SEARCHER_LOCAL;udsi["news"]=_MSG_SEARCHER_NEWS;udsi["save"]=_MSG_SEARCHCONTROL_SAVE;udsi["keep"]=_MSG_SEARCHCONTROL_KEEP;udsi["include"]=_MSG_SEARCHCONTROL_INCLUDE;udsi["copy"]=_MSG_SEARCHCONTROL_COPY;udsi["close"]=_MSG_SEARCHCONTROL_CLOSE;udsi["sponsored-links"]=_MSG_SEARCHCONTROL_SPONSORED_LINKS;udsi["see-more"
]=_MSG_SEARCHCONTROL_SEE_MORE;udsi["watermark"]=_MSG_SEARCHCONTROL_WATERMARK;udsi["search-location"]=_MSG_SEARCHER_CONFIG_SET_LOCATION;udsi["disable-address-lookup"]=_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;udsi["sort-by-date"]=_MSG_SORT_BY_DATE;udsi["pbg"]=_MSG_BRANDING_STRING;udsi["n-minutes-ago"]=_MSG_MINUTES_AGO;udsi["n-hours-ago"]=_MSG_HOURS_AGO;udsi["one-hour-ago"]=_MSG_ONE_HOUR_AGO;udsi["all-n-related"]=_MSG_NEWS_ALL_N_RELATED;udsi["related-articles"]=_MSG_NEWS_RELATED;var udsw=new Array;
udsw[0]=_MSG_MONTH_ABBR_JAN;udsw[1]=_MSG_MONTH_ABBR_FEB;udsw[2]=_MSG_MONTH_ABBR_MAR;udsw[3]=_MSG_MONTH_ABBR_APR;udsw[4]=_MSG_MONTH_ABBR_MAY;udsw[5]=_MSG_MONTH_ABBR_JUN;udsw[6]=_MSG_MONTH_ABBR_JUL;udsw[7]=_MSG_MONTH_ABBR_AUG;udsw[8]=_MSG_MONTH_ABBR_SEP;udsw[9]=_MSG_MONTH_ABBR_OCT;udsw[10]=_MSG_MONTH_ABBR_NOV;udsw[11]=_MSG_MONTH_ABBR_DEC;udsi["month-abbr"]=udsw;udsi["directions"]=_MSG_DIRECTIONS;udsi["clear-results"]=_MSG_CLEAR_RESULTS;udsi["show-one-result"]=_MSG_SHOW_ONE_RESULT;udsi["show-more-results"
]=_MSG_SHOW_MORE_RESULTS;udsi["show-all-results"]=_MSG_SHOW_ALL_RESULTS;udsi["settings"]=_MSG_SETTINGS;udsi["search"]=_MSG_SEARCH;udsi["search-uc"]=_MSG_SEARCH_UC;udsi["powered-by"]=_MSG_POWERED_BY;udsi["sa"]="Search Appliance";udsi["book"]="Book";
Function.prototype.inherits=function(uds){var udsa=function(){}
;udsa.prototype=uds.prototype;this.prototype=new udsa;this.prototype.__super__=function(udsb,udsd,udsf,udse){var udsh=Array.prototype.splice.apply(arguments,[1,arguments.length]);return udsb.apply(this,udsh)}
}
;var _json_cache_defeater_=0;function udsX(uds){return uds+"&key="+UDS_ApiKey+"&v="+UDS_Version}
function udsN(uds){var udsa=document.getElementsByTagName("head")[0];var udsb=document.createElement("script");udsb.type="text/javascript";udsb.charset="utf-8";var udsd=udsX(uds);if(udsH()||udsZ()){udsd=udsd+"&nocache="+_json_cache_defeater_++}udsb.src=udsd;var udsf=function(){var udsh=udsb.parentNode;udsh.removeChild(udsb);delete udsb}
;var udse=function(udsh){var udsk=(udsh?udsh:window.event).target?(udsh?udsh:window.event).target:(udsh?udsh:window.event).srcElement;if(udsk.readyState=="loaded"||udsk.readyState=="complete"){udsf()}}
;if(navigator.product=="Gecko"){udsb.onload=udsf}else{udsb.onreadystatechange=udse}udsa.appendChild(udsb)}
function udsG(uds,udsa){return function(){return udsa.apply(uds,arguments)}
}
function udst(uds,udsa,udsb){return function(){return udsa.apply(uds,udsb)}
}
function udsD(uds){while(uds.firstChild){uds.removeChild(uds.firstChild)}}
function udsU(uds,udsa){if(uds){try{udsD(uds);uds.appendChild(udsa)}catch(udsb){}}return udsa}
function udsg(uds,udsa){try{uds.appendChild(udsa)}catch(udsb){}return udsa}
function udsV(uds,udsa){uds.innerHTML=udsa}
function udsT(uds){return document.createTextNode(uds?uds:"")}
function udsl(uds,udsa){var udsb=document.createElement("div");if(uds){udsb.innerHTML=uds}if(udsa){udsb.className=udsa}return udsb}
function udsn(uds){var udsa=document.createElement("div");if(uds){udsa.className=uds}return udsa}
function udsS(uds,udsa){var udsb=document.createElement("span");if(uds){udsg(udsb,udsT(uds))}if(udsa){udsb.className=udsa}return udsb}
function udsC(uds,udsa,udsb){var udsd=document.createElement("table");udsd.setAttribute("cellSpacing",uds?uds:0);udsd.setAttribute("cellPadding",udsa?udsa:0);if(udsb){udsd.className=udsb}return udsd}
function udsy(uds,udsa,udsb){var udsd=uds.insertRow(-1);if(!udsd){alert(udsd)}for(var udsf=0;udsf<udsa;udsf++){udsr(udsd,udsb)}return udsd}
function udsr(uds,udsa){var udsb=uds.insertCell(-1);if(udsa){udsb.className=udsa}return udsb}
function udsB(uds,udsa,udsb,udsd){var udsf=document.createElement("img");udsf.src=uds;if(udsa){udsf.width=udsa}if(udsb){udsf.height=udsb}if(udsd){udsf.className=udsd}return udsf}
function udsW(uds,udsa,udsb,udsd){var udsf;if(udsH()){udsf=udsn(udsd);udsf.style.filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+uds+'")';udsf.style.width=udsa+"px";udsf.style.height=udsb+"px"}else{udsf=udsB(uds,null,null,udsd)}return udsf}
function udsM(uds,udsa,udsb,udsd){var udsf=document.createElement("a");udsf.href=uds;if(udsa){if(udsd){udsg(udsf,udsS(udsa,udsd))}else{udsg(udsf,udsT(udsa))}}if(udsb){udsf.target=udsb}return udsf}
function udsp(uds,udsa,udsb,udsd){var udsf=udsl(null,udsd);var udse=document.createElement("a");udse.href=uds;var udsh=udsl(null,udsd);udsh.innerHTML=udsa;udse.appendChild(udsh);if(udsd){udse.className=udsd}if(udsb){udse.target=udsb}udsf.appendChild(udse);return udsf}
function udsQ(uds){var udsa=document.createElement("form");if(uds){udsa.className=uds}return udsa}
function udsK(uds,udsa){var udsb=document.createElement("input");udsb.type="submit";udsb.value=uds;if(udsa){udsb.className=udsa}return udsb}
function udsR(uds,udsa,udsb){var udsd=document.createElement("input");udsd.setAttribute("autoComplete","off");udsd.type="text";if(uds==-1){udsm(udsd,"util-css-expand")}else{udsd.size=uds>0?uds:10}if(udsa){udsm(udsd,udsa)}if(udsb){udsd.value=udsb}return udsd}
function udsL(uds,udsa,udsb,udsd){var udsf=document.createElement("input");udsf.type="checkbox";udsf.name=uds;udsf.value=udsa;if(udsd){udsf.className=udsd}if(udsb){udsf.checked=udsb}return udsf}
function udsA(uds,udsa){uds.className=udsa}
function udsm(uds,udsa){uds_(uds,udsa)}
function udsx(uds,udsa){uds1(uds,udsa)}
function uds0(uds,udsa){if(uds==null||uds.className==null)return false;var udsb=uds.className.split(" ");for(var udsd=0;udsd<udsb.length;udsd++){if(udsb[udsd]==udsa){return true}}return false}
function uds_(uds,udsa){if(uds0(uds,udsa))return;uds.className+=" "+udsa}
function uds1(uds,udsa){if(uds.className==null)return;var udsb=uds.className.split(" ");var udsd=[];var udsf=false;for(var udse=0;udse<udsb.length;udse++){if(udsb[udse]!=udsa){if(udsb[udse]){udsd.push(udsb[udse])}}else{udsf=true}}if(udsf){uds.className=udsd.join(" ")}}
var udsI="";function uds2(uds){var udsa=uds.toLowerCase().split(".");if(udsa.length<2){udsI=".com"}var udsb=udsa.pop();var udsd=udsa.pop();if(udsb.length==2){if(udsJ[udsd]&&udsJ[udsd][udsb]==1){udsI="."+udsd+"."+udsb}else{udsI="."+udsb}}else{udsI=".com"}return udsI}
var udsJ={co:{ck:1,cr:1,hu:1,id:1,il:1,"in":1,je:1,jp:1,ke:1,kr:1,ls:1,nz:1,th:1,ug:1,uk:1,ve:1,vi:1,za:1},com:{ag:1,ar:1,au:1,bo:1,br:1,bz:1,co:1,cu:1,"do":1,ec:1,fj:1,gi:1,gr:1,gt:1,hk:1,jm:1,ly:1,mt:1,mx:1,my:1,na:1,nf:1,ni:1,np:1,pa:1,pe:1,ph:1,pk:1,pr:1,py:1,sa:1,sg:1,sv:1,tr:1,tw:1,ua:1,uy:1,vc:1,vn:1},off:{ai:1}};function uds3(uds){var udsa=uds.toLowerCase().split(".");if(udsa.length<2){return false}var udsb=udsa.pop();var udsd=udsa.pop();if((udsd=="igoogle"||udsd=="gmodules")&&udsb=="com"
){return true}if(udsb.length==2&&udsa.length>0){if(udsJ[udsd]&&udsJ[udsd][udsb]==1){udsd=udsa.pop()}}return udsd=="google"}
function udsO(uds){if(uds in udsP){return udsP[uds]}return udsP[uds]=navigator.userAgent.toLowerCase().indexOf(uds)!=-1}
var udsP={};function udsH(){return udsO("msie")}
function udsZ(){return udsO("safari")||udsO("konqueror")}
;
function udsc(){}
udsc.q="gs-result";udsc.r="gs-title";udsc.P="gs-snippet";udsc.E="gs-visibleUrl";udsc.cb="gs-visibleUrl-long";udsc.Wb="gs-visibleUrl-short";udsc.$c="gs-watermark";udsc.Wc="gs-results-attribution";udsc.Nb="gs-address";udsc.Vb="gs-street";udsc.Ob="gs-city";udsc.Sb="gs-region";udsc.Oc="gs-country";udsc.Pb="gs-phone";udsc.Pc="gs-directions";udsc.Mc="gs-author";udsc.Rb="gs-publisher";udsc.Sc="gs-location";udsc.Nc="gs-clusterUrl";udsc.ea="gs-image-box";udsc.wa="gs-text-box";udsc.Tc="gs-metadata";udsc.Xc=
"gs-row-1";udsc.Yc="gs-row-2";udsc.Ub="gs-shadow";udsc.Vc="gs-pages";udsc.Uc="gs-page-edge";udsc.D="gs-image";udsc.Zc="gs-size";udsc.Qb="gs-publishedDate";udsc.Tb="gs-relativePublishedDate";udsc.Xb="gs-webAd";udsc.Rc="gs-localAd";udsc.bb="gs-ad-marker";udsc.V="gs-line";udsc.Qc="gs-divider";udsc.wc="gsc-control";udsc.zc="gsc-narrow";udsc.Jb="gsc-search-box";udsc.Kb="gsc-search-button";udsc.Db="gsc-clear-button";udsc.Fb="gsc-input";udsc.ra="gsc-branding";udsc.Cb="gsc-branding-vertical";udsc.pc="gsc-branding-img"
;udsc.qc="gsc-branding-user-defined";udsc.Sa="gsc-branding-img-noclear";udsc.ta="gsc-branding-text";udsc.Xa="gsc-resultsRoot";udsc.Ec="gsc-results";udsc.Wa="gsc-result";udsc.Dc="gsc-resultsHeader";udsc.T="gsc-resultsbox-invisible";udsc.U="gsc-resultsbox-visible";udsc.xc="gsc-expansionArea";udsc.oc="gsc-ad-box";udsc.Kc="gsc-twiddleRegionCell";udsc.rc="gsc-configLabelCell";udsc.sc="gsc-configLabel";udsc.Lc="gsc-twiddle";udsc.da="gsc-twiddle-closed";udsc.va="gsc-twiddle-opened";udsc.Jc="gsc-title";udsc.Gc=
"gsc-stats";udsc.Gb="gsc-keeper";udsc.Cc="gsc-result-selector gsc-one-result";udsc.Bc="gsc-result-selector gsc-more-results";udsc.Ac="gsc-result-selector gsc-all-results";udsc.Fc="gsc-results-selector";udsc.Ib="gsc-one-result-active";udsc.Hb="gsc-more-results-active";udsc.Bb="gsc-all-results-active";udsc.Mb="gsc-tabsArea";udsc.Lb="gsc-tabsAreaInvisible";udsc.Ic="gsc-tabHeader";udsc.$a="gsc-tabhActive";udsc.ab="gsc-tabhInactive";udsc.Ya="gsc-tabdActive";udsc.Za="gsc-tabdInactive";udsc.Hc="gsc-tabData"
;udsc.Eb="gsc-config";udsc.Va="gsc-configSetting";udsc.ca="gsc-configSettingSubmit";udsc.Ua="gsc-configSettingCheckbox";udsc.Ta="gsc-configSettingCheckboxLabel";udsc.uc="gsc-configSettingInput";udsc.tc="gsc-configSettingInputLabel";udsc.yc="gsc-locationConfig";udsc.Jd="as-results";udsc.Ra="as-result-vertical";udsc.Ab="as-result-horizontal";udsc.zb="as-result-cell";udsc.Id="as-branding-cell";
GSearch.BASE=UDS_ServiceBase;GSearch.LARGE_RESULTSET="large";GSearch.SMALL_RESULTSET="small";GSearch.LARGE_RESULTS=8;GSearch.LARGE_ADS=4;GSearch.SMALL_RESULTS=4;GSearch.SMALL_ADS=2;GSearch.KEEP_SWEEPER_DELAY=5000;GSearch.LINK_TARGET_TOP="_top";GSearch.LINK_TARGET_SELF="_self";GSearch.LINK_TARGET_PARENT="_parent";GSearch.LINK_TARGET_BLANK="_blank";GSearch.ORDER_BY_RELEVANCE="order-by-relevance";GSearch.ORDER_BY_DATE="order-by-date";function GSearch(){this.Kd=null;this.Y=null;this.nc=0;this.Oa=0;this.mb=
true;this.N={width:100,height:75};this.Q=GSearch.LINK_TARGET_BLANK;this.hc=1;this.setResultSetSize(GSearch.SMALL_RESULTSET);this.clearResults();this.ib=null;this.jb=null;this.xb=null;this.qb=null;this.qa=null;this.oa=null;this.Fa=null;this.k="null";this.e=null}
GSearch.prototype.setQueryAddition=function(uds){if(uds==null||uds==""){this.e=null}else{this.e=uds}}
;GSearch.prototype.I=function(uds,udsa){var udsb=GSearch.BASE+this.u+"?callback="+uds+"&context="+udsa+"&lstkp="+this.fd()+"&rsz="+this.Ja+"&hl="+UDS_CurrentLocale;if(this.ob){udsb+="&gss="+this.ob}if(UDS_JSHash){udsb+="&sig="+UDS_JSHash}return udsb}
;GSearch.prototype.setLinkTarget=function(uds){this.Q=uds}
;GSearch.prototype.d=function(){if(this.Q&&this.Q!=""){return this.Q}else{return null}}
;GSearch.prototype.dc=function(){this.nc++;this.Oa++;if(this.Fa){clearTimeout(this.Fa)}this.Fa=setTimeout(udst(this,this.execute,[null]),GSearch.KEEP_SWEEPER_DELAY)}
;GSearch.prototype.fd=function(){clearTimeout(this.Fa);var uds=this.Oa;this.Oa=0;return uds}
;GSearch.prototype.nb=function(){if(this.ib==null){this.ib="gsc-"+this.k+"Result"}return this.ib}
;GSearch.prototype.J=function(){if(this.jb==null){this.jb="gs-"+this.k+"Result"}return this.jb}
;GSearch.prototype.qd=function(){if(this.xb==null){this.xb=udsi[this.k]}if(this.qa){return this.qa}else{return this.xb}}
;GSearch.prototype.od=function(){if(this.qb==null){this.qb=udsi[this.k]}if(this.qa){return this.qa}else{return this.qb}}
;GSearch.prototype.getResultSetSize=function(){return this.Ja}
;GSearch.prototype.setResultSetSize=function(uds){switch(uds){case GSearch.LARGE_RESULTSET:this.Ja=GSearch.LARGE_RESULTSET;break;default:case GSearch.SMALL_RESULTSET:this.Ja=GSearch.SMALL_RESULTSET;break}}
;GSearch.prototype.execute=function(uds){var udsa=this.m(uds,null,null);udsN(udsa)}
;GSearch.prototype.getExecuteUrl=function(uds,udsa,udsb){var udsd=this.m(uds,udsa,udsb);return udsX(udsd)}
;GSearch.prototype.s=function(uds){var udsa="http://code.google.com/apis/ajaxsearch/faq.html";var udsb=udsi["watermark"]+" - "+this.gd();var udsd=udsp(udsa,udsb,"_blank",udsc.$c);udsg(uds,udsd)}
;GSearch.prototype.gd=function(){var uds=new Date;var udsa=uds.getMonth()+1+"/"+uds.getFullYear();return udsa}
;GSearch.prototype.Da=function(uds){var udsa;var udsb=uds.getFullYear();var udsd=uds.getMonth();var udsf=udsi["month-abbr"][udsd];var udse=uds.getDate();if(udse<10){udse="0"+udse}switch(UDS_ShortDatePattern){case "MDY":udsa=udsf+" "+udse+", "+udsb;break;case "YMD":udsa=udsb+" "+udsf+" "+udse;break;default:case "DMY":udsa=udse+" "+udsf+" "+udsb;break}return udsa}
;GSearch.Yb=3600000;GSearch.bd=60000;GSearch.ad=86400000;GSearch.prototype.cc=function(uds){var udsa=new Date;var udsb=udsa.getTime();var udsd=uds.getTime();var udsf;if(udsb<udsd){return udsi["n-minutes-ago"](2)}var udse=udsb-udsd;if(udse<GSearch.Yb){var udsh=parseInt(udse/GSearch.bd);if(udsh<=1){udsf=2}else{udsf=udsh}return udsi["n-minutes-ago"](udsf)}if(udse<GSearch.ad){var udsk=parseInt(udse/GSearch.Yb);if(udsk<=1){return udsi["one-hour-ago"]}else{udsf=udsk;return udsi["n-hours-ago"](udsf)}}return this.Da(
uds)}
;GSearch.prototype.clearResults=function(){this.Ld=null;this.results=new Array;this.adResults=new Array}
;GSearch.prototype.bc=function(){if(this.ac){this.ac()}}
;GSearch.prototype.onSearchComplete=function(uds,udsa,udsb,udsd){if(uds==null&&udsa==204){return}if(uds&&uds.results&&uds.results.length>0){this.results=uds.results}else{this.results=new Array}if(uds&&uds.adResults&&uds.adResults.length>0){this.adResults=uds.adResults}else{this.adResults=new Array}this.completionStatus=udsa;this.hashStatus=udsd;this.completionFailureDetails=udsb;if(uds&&uds.resultAttribution&&uds.resultAttribution!=null&&uds.resultAttribution!=""){this.Ia=uds.resultAttribution}else{
this.Ia=null}if(this.mb){this.$b()}this.bc()}
;GSearch.prototype.getAttribution=function(){var uds=null;if(this.Ia){uds=udsl(this.Ia,udsc.Wc)}return uds}
;GSearch.prototype.$b=function(){var uds;var udsa;for(uds=0;uds<this.results.length;uds++){udsa=this.results[uds];this.F(udsa)}for(uds=0;uds<this.adResults.length;uds++){udsa=this.adResults[uds];this.fa(udsa)}}
;GSearch.prototype.fa=function(uds){if(uds.html){delete uds.html}}
;GSearch.prototype.setSearchCompleteCallback=function(uds,udsa,udsb){if(!udsb){udsb=[null]}this.ac=udst(uds,udsa,udsb)}
;GSearch.AllocateCompletionMapContext=function(uds,udsa){var udsb=false;var udsd=null;if(uds.length){for(var udsf=0;udsf<uds.length;udsf++){if(uds[udsf]==null){uds[udsf]=udsa;udsd=udsf;udsb=true;break}}}if(!udsb){udsd=uds.length;uds.push(udsa)}return udsd}
;GSearch.prototype.setUserDefinedLabel=function(uds){this.qa=uds}
;GSearch.prototype.setUserDefinedClassSuffix=function(uds){this.oa=uds}
;GSearch.prototype.setNoHtmlGeneration=function(){this.mb=false}
;GSearch.scaleImage=function(uds,udsa,udsb,udsd){var udsf=udsb.width/uds;var udse=udsb.height/udsa;var udsh=Math.min(udsf,udse);var udsk=Math.min(udsh,1);var udsj=new Object;udsj.width=Math.round(uds*udsk);udsj.height=Math.round(udsa*udsk);if(udsd){udsd.width=udsj.width;udsd.height=udsj.height}return udsj}
;GSearch.VERTICAL_BRANDING=1;GSearch.HORIZONTAL_BRANDING=2;GSearch.getBranding=function(uds,udsa){var udsb=udsn(udsc.ra);var udsd=udsC(null,null,udsc.ra);udsg(udsb,udsd);var udsf=true;if(udsa){if(udsa==GSearch.VERTICAL_BRANDING){udsf=false;udsm(udsb,udsc.Cb);udsm(udsd,udsc.Cb)}else if(udsa==GSearch.HORIZONTAL_BRANDING){udsf=true}else{udsf=true}}var udse=udsy(udsd,0);var udsh;var udsk;if(udsf){udsh=udse;udsk=udse}else{udsh=udse;udsk=udsy(udsd,0)}var udsj=udsr(udsh,udsc.ta);var udso=udsr(udsk,udsc.Sa)
;var udsq=udsl(udsi["powered-by"],udsc.ta);var udsu=UDS_ServiceBase+"/css/small-logo.png";var udsv=udsW(udsu,51,15,udsc.Sa);udsg(udsj,udsq);udsg(udso,udsv);if(uds){udsD(uds);udsg(uds,udsb)}return udsb}
;GSearch.setOnLoadCallback=function(uds){var udsa=window;if(udsa.addEventListener){udsa.addEventListener("load",uds,false)}else if(udsa.attachEvent){udsa.attachEvent("onload",uds)}else{udsa["onload"]=uds}}
;
function GwebSearch(){GSearch.call(this);this.k="web";this.u="/GwebSearch";this.h=null;this.ga=false;this.Ba=null}
GwebSearch.inherits(GSearch);GwebSearch.RESULT_CLASS="GwebSearch";GwebSearch.AD_CLASS="GwebSearch.ad";GwebSearch.c=new Array;GwebSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GwebSearch.c[udse];GwebSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GwebSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GwebSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GwebSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}if(this.h&&this.ga==false){udsh=udsh+" site:"+this.h}if(this.h&&this.ga==true){udse=udse+"&cx="+this.h;if(this.Ba!=null){udsh=udsh+" more:"+this.Ba}}udse=udse+"&q="+encodeURIComponent(udsh)}return udse}

;GwebSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);udsb=udsl(uds.content,udsc.P);udsg(udsa,udsb);udsb=udsp("#",uds.visibleUrl,null,udsc.E);udsg(udsa,udsb);udsm(udsb,udsc.Wb);var udsd=uds.unescapedUrl.indexOf(uds.visibleUrl);var udsf=uds.visibleUrl;if(udsd!=-1&&udsd!=0){udsf=uds.unescapedUrl.substring(udsd)}udsb=udsp("#",udsf,null,udsc.E);udsm(udsb,udsc.cb);udsg(
udsa,udsb);uds.html=udsa;this.s(uds.html)}
;GwebSearch.prototype.fa=function(uds){if(uds.html){delete uds.html}var udsa=udsn(udsc.Xb);udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);if(uds.content1){udsb=udsl(uds.content1,udsc.V);udsg(udsa,udsb)}if(uds.content2){udsb=udsl(uds.content2,udsc.V);udsg(udsa,udsb)}udsb=udsp("#",uds.visibleUrl,null,udsc.E);var udsd=udsB(uds.impressionUrl,12,12,udsc.bb);udsg(udsb,udsd);udsg(udsa,udsb);uds.html=udsa;this.s(uds.html)}
;GwebSearch.prototype.setSiteRestriction=function(uds,udsa){if(uds==null||uds==""){this.h=null;this.ga=false;this.Ba=null}else{var udsb=uds.match(/^\d{21}:.*/);if(udsb){this.h=uds;this.ga=true;if(udsa){this.Ba=udsa}}else{this.h=uds;this.ga=false}}}
;
function GadSearch(uds,udsa,udsb){GSearch.call(this);this.k="ad";this.u="/GadSearch";this.jc();if(udsb&&uds==null&&udsa==null){this.bootOptions=udsb;this.boot()}else{this.setRoot(uds);if(udsa){this.kc(udsa)}}}
GadSearch.inherits(GSearch);GadSearch.RESULT_CLASS="GwebSearch";GadSearch.AD_CLASS="GwebSearch.ad";GadSearch.c=new Array;GadSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GadSearch.c[udse];GadSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GadSearch.prototype.md=function(uds){this.setResultSetSize(GadSearch.p[this.b.B].sb);var udsa=this.m(uds,null,null);udsN(udsa)}
;GadSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GadSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GadSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;udse=udse+"&q="+encodeURIComponent(udsh)}return udse}
;GadSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);udsb=udsl(uds.content,udsc.P);udsg(udsa,udsb);udsb=udsp("#",uds.visibleUrl,null,udsc.E);udsg(udsa,udsb);udsm(udsb,udsc.Wb);var udsd=uds.unescapedUrl.indexOf(uds.visibleUrl);var udsf=uds.visibleUrl;if(udsd!=-1&&udsd!=0){udsf=uds.unescapedUrl.substring(udsd)}udsb=udsp("#",udsf,null,udsc.E);udsm(udsb,udsc.cb);udsg(udsa,
udsb);uds.html=udsa;this.s(uds.html)}
;GadSearch.prototype.fa=function(uds){if(uds.html){delete uds.html}var udsa=udsn(udsc.Xb);udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);if(uds.content1){udsb=udsl(uds.content1,udsc.V);udsg(udsa,udsb)}if(uds.content2){udsb=udsl(uds.content2,udsc.V);udsg(udsa,udsb)}udsb=udsp("#",uds.visibleUrl,null,udsc.E);var udsd=udsB(uds.impressionUrl,12,12,udsc.bb);udsg(udsb,udsd);udsg(udsa,udsb);uds.html=udsa;this.s(uds.html)}
;GadSearch.TYPE_H3="h3";GadSearch.TYPE_V3="v3";GadSearch.TYPE_V6="v6";GadSearch.p={h3:{eb:udsc.Ab,yb:"740px",pb:"85px",B:GadSearch.TYPE_H3,C:false,H:3,sb:GSearch.SMALL_RESULTSET},v3:{eb:udsc.Ra,yb:"230px",pb:"205px",B:GadSearch.TYPE_V3,C:true,H:3,sb:GSearch.SMALL_RESULTSET},v6:{eb:udsc.Ra,yb:"230px",pb:"410px",B:GadSearch.TYPE_V6,C:true,H:6,sb:GSearch.LARGE_RESULTSET}};GadSearch.prototype.setRoot=function(uds){this.ba=uds;udsD(this.ba)}
;GadSearch.prototype.jc=function(){this.b=new Object;var uds=GadSearch.TYPE_V3;this.b.B=GadSearch.p[uds].B;this.b.C=GadSearch.p[uds].C;this.b.H=GadSearch.p[uds].H;this.b.gb=null;this.lc()}
;GadSearch.prototype.kc=function(uds){this.jc();for(var udsa in uds){var udsb=uds[udsa];switch(udsa){case "type":switch(udsb){case GadSearch.TYPE_H3:case GadSearch.TYPE_V3:case GadSearch.TYPE_V6:this.b.B=GadSearch.p[udsb].B;this.b.C=GadSearch.p[udsb].C;this.b.H=GadSearch.p[udsb].H;break;default:udsb=GadSearch.TYPE_V3;this.b.B=GadSearch.p[udsb].B;this.b.C=GadSearch.p[udsb].C;this.b.H=GadSearch.p[udsb].H;break}break;case "colors":var udsd="";if(uds.colors.background){udsd+="&cb="+uds.colors.background}
if(uds.colors.link){udsd+="&cl="+uds.colors.link}if(uds.colors.text){udsd+="&ct="+uds.colors.text}if(uds.colors.text){udsd+="&cu="+uds.colors.url}this.b.gb=udsd;break}}this.lc()}
;GadSearch.prototype.lc=function(){var uds="";var udsa;udsa=this.b.B;uds+="&aqt="+udsa;if(this.b.gb){uds+=this.b.gb}this.zd=uds}
;GadSearch.prototype.execute=function(uds){var udsa=(new Date).getTime();this.u="/GadSearch/"+udsa;var udsb=this.m("nothing","x","y");this.u="/GadSearch";var udsd=uds;if(this.e){udsd=udsd+" "+this.e}udsb=udsb+"&boot="+encodeURIComponent(udsd)+this.zd;var udsf="&dt="+(new Date).getTime();udsb+=udsf;var udse=this.hd(udsb);udsU(this.ba,udse)}
;GadSearch.prototype.hd=function(uds){var udsa=this.b.B;var udsb;if(udsH()){udsb=document.createElement("<iframe frameborder=no scrolling=no>")}else{udsb=document.createElement("iframe");udsb.setAttribute("frameborder","no");udsb.setAttribute("scrolling","no")}udsb.className=GadSearch.p[udsa].eb;udsb.style.width=GadSearch.p[udsa].yb;udsb.style.height=GadSearch.p[udsa].pb;udsb.style.border="none";udsb.id=(new Date).getTime();udsb.src=uds;return udsb}
;GadSearch.prototype.boot=function(){if(!this.bootOptions){alert("options not set");return}this.setRoot(document.getElementById(this.bootOptions.resultsRoot));this.kc(this.bootOptions);this.setLinkTarget(GSearch.LINK_TARGET_PARENT);this.setSearchCompleteCallback(this,GadSearch.prototype.ed,[null]);this.md(this.bootOptions.bootQuery)}
;GadSearch.prototype.ed=function(){if(this.adResults&&this.adResults.length>0){var uds=this.adResults.length;if(uds>this.H){uds=this.H}var udsa;var udsb;var udsd=null;if(this.b.C){udsb=udsC(null,null,udsc.Ra)}else{udsb=udsC(null,null,udsc.Ab)}for(var udsf=0;udsf<uds;udsf++){var udse=this.adResults[udsf];var udsh=udse.html.cloneNode(true);if(this.b.C){udsd=udsy(udsb,0)}else{if(udsd==null){udsd=udsy(udsb,0)}}udsa=udsr(udsd,udsc.zb);udsa.appendChild(udsh)}udsd=udsy(udsb,0);udsa=udsr(udsd,udsc.zb);if(
!this.b.C){udsa.setAttribute("colspan",uds)}var udsk=udsl("Ads by Google",udsc.ra);udsg(udsa,udsk);this.ba.appendChild(udsb)}}
;
function GsaSearch(uds){GSearch.call(this);this.dd=uds;this.k="sa";this.u="/ajax"}
GsaSearch.inherits(GSearch);GsaSearch.RESULT_CLASS="GsaSearch";GsaSearch.AD_CLASS="GsaSearch.ad";GsaSearch.c=new Array;GsaSearch.RawCompletion=function(uds,udsa,udsb){var udsd=0;if(uds){udsd=parseInt(uds)}var udsf=GsaSearch.c[udsd];GsaSearch.c[udsd]=null;udsf.onSearchComplete(udsa,udsb)}
;GsaSearch.NEXT_PAGE="next";GsaSearch.PREV_PAGE="prev";GsaSearch.prototype.execute=function(uds,udsa){var udsb=this.m(uds,null,null,udsa);udsN(udsb)}
;GsaSearch.prototype.m=function(uds,udsa,udsb,udsd){var udsf;if(udsb==null){udsf=GSearch.AllocateCompletionMapContext(GsaSearch.c,this)}else{udsf=udsb}var udse;if(udsa==null){udse="GsaSearch.RawCompletion"}else{udse=udsa}var udsh=this.I(udse,udsf,udsd);if(uds){var udsk=uds;if(this.e){udsk=udsk+" "+this.e}udsh=udsh+"&q="+encodeURIComponent(udsk)}return udsh}
;GsaSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);udsb=udsl(uds.content,udsc.P);udsg(udsa,udsb);udsb=udsp("#",uds.visibleUrl,null,udsc.E);udsg(udsa,udsb);udsm(udsb,udsc.cb);uds.html=udsa;this.s(uds.html)}
;GsaSearch.kd="&ajax_version=1.0&client=default_frontend&site=default_collection&ie=UTF-8&oe=UTF-8";GsaSearch.prototype.I=function(uds,udsa,udsb){var udsd=this.dd+this.u+"?ajax_callback="+uds+"&ajax_context="+udsa+"&hl="+UDS_CurrentLocale+GsaSearch.kd+"&num="+this.Ha+this.pd(udsb);return udsd}
;GsaSearch.prototype.dc=function(){this.nc++;this.Oa++}
;GsaSearch.prototype.onSearchComplete=function(uds,udsa){if(uds==null&&udsa==204){return}if(uds&&uds.results&&uds.results.length>0){this.results=new Array;for(var udsb=0;udsb<uds.results.length;udsb++){var udsd=uds.results[udsb];var udsf=new Object;udsf.GsearchResultClass=udsd.GsearchResultClass;udsf.unescapedUrl=udsd.unescapedUrl;udsf.url=udsd.url;udsf.visibleUrl=udsd.visibleUrl;udsf.title=udsd.title;udsf.titleNoFormatting=udsd.titleNoFormatting;udsf.content=udsd.snippet;this.results.push(udsf)}
this.La=uds.start_index;this.Ca=uds.end_index;this.kb=uds.est}else{this.results=new Array;this.La=0;this.Ca=0;this.kb=0}this.completionStatus=udsa;this.hashStatus=200;this.completionFailureDetails="";this.Ia=null;if(this.mb){this.$b()}this.bc()}
;GsaSearch.prototype.setResultSetSize=function(uds){this.__super__(GSearch.prototype.setResultSetSize,uds);switch(this.Ja){case GSearch.LARGE_RESULTSET:this.Ha=8;break;case GSearch.SMALL_RESULTSET:this.Ha=4;break}}
;GsaSearch.prototype.pd=function(uds){var udsa="";if(uds&&this.completionStatus==200&&this.La&&this.Ca&&this.kb){if(uds==GsaSearch.NEXT_PAGE){if(this.Ca<this.kb){udsa="&start="+this.Ca}}else if(uds==GsaSearch.PREV_PAGE){var udsb;if(this.La>this.Ha+1){udsb=this.La-(this.Ha+1)}else{udsb=0}udsa="&start="+udsb}}return udsa}
;
function GnewsSearch(){GSearch.call(this);this.k="news";this.u="/GnewsSearch";this.Md=null;this.n=false;this.Aa=true;this.Y=udsG(this,GnewsSearch.prototype.ja);this.ya="gsc-newsConfig";this.f=null}
GnewsSearch.inherits(GSearch);GnewsSearch.RESULT_CLASS="GnewsSearch";GnewsSearch.c=new Array;GnewsSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GnewsSearch.c[udse];GnewsSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GnewsSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GnewsSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GnewsSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}if(this.h){udsh=udsh+" source:"+this.h}udse=udse+"&q="+encodeURIComponent(udsh);if(this.n){udse=udse+"&scoring=d"}}return udse}
;GnewsSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);udsb=udsl(uds.publisher,udsc.Rb);udsg(udsa,udsb);var udsd=uds.location.split(",");if(udsd.length>1){var udsf=", "+udsd[udsd.length-1];udsb=udsl(udsf,udsc.Sc);udsg(udsa,udsb)}var udse=new Date(uds.publishedDate);udsb=udsl(" - "+this.Da(udse),udsc.Qb);udsg(udsa,udsb);var udse=new Date(uds.publishedDate);udsb=udsl(
" - "+this.cc(udse),udsc.Tb);udsg(udsa,udsb);udsb=udsl(uds.content,udsc.P);udsg(udsa,udsb);if(uds.clusterUrl&&uds.clusterUrl!=""){udsb=udsp(uds.clusterUrl,udsi["related-articles"],this.d(),udsc.Nc);udsg(udsa,udsb)}uds.html=udsa;this.s(uds.html)}
;GnewsSearch.prototype.setSiteRestriction=function(uds){if(uds==null||uds==""){this.h=null}else{this.h=uds.replace(/\s/g,"_")}}
;GnewsSearch.prototype.setResultOrder=function(uds){if(uds==GSearch.ORDER_BY_DATE){this.n=true}else if(uds==GSearch.ORDER_BY_RELEVANCE){this.n=false}else{this.n=false}}
;GnewsSearch.prototype.ja=function(uds,udsa){if(udsa){if(this.f==null){var udsb=udsn(udsc.Va);this.f=udsL(null,"0",this.n?true:false,udsc.Ua);udsg(udsb,this.f);udsg(udsb,udsl(udsi["sort-by-date"],udsc.Ta));var udsd=udsn(udsc.ca);udsg(udsd,udsK(udsi["close"],udsc.ca));udsg(udsb,udsd);udsg(uds,udsb);this.f.focus()}else{this.f.checked=this.n?true:false;this.f.focus()}}else{if(this.f){if(this.f.checked){this.setResultOrder(GSearch.ORDER_BY_DATE)}else{this.setResultOrder(GSearch.ORDER_BY_RELEVANCE)}}}
}
;
function GimageSearch(){GSearch.call(this);this.hc=4;this.k="image";this.u="/GimageSearch"}
GimageSearch.inherits(GSearch);GimageSearch.RESULT_CLASS="GimageSearch";GimageSearch.AD_CLASS="GwebSearch.ad";GimageSearch.c=new Array;GimageSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GimageSearch.c[udse];GimageSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GimageSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GimageSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GimageSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}udse=udse+"&q="+encodeURIComponent(udsh)}return udse}
;GimageSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb=GSearch.scaleImage(uds.tbWidth,uds.tbHeight,this.N);var udsd=udsB(uds.tbUrl,udsb.width,udsb.height,udsc.D);var udsf=udsM(uds.originalContextUrl,null,this.d(),udsc.D);udsA(udsf,udsc.D);udsg(udsf,udsd);udsg(udsa,udsf);var udse;udse=udsp(uds.originalContextUrl,uds.title,this.d(),udsc.r);udsg(udsa,udse);var udsh=uds.width+" x "+uds.height+" px";udse=udsl(udsh,udsc.Zc);udsg(udsa,udse)
;udse=udsp("#",uds.visibleUrl,null,udsc.E);udsg(udsa,udse);uds.html=udsa;this.s(uds.html)}
;
function GlocalSearch(){GSearch.call(this);this.o=null;this.A="San Francisco, CA";this.w=null;this.ia=true;this.X=false;if(window.location&&window.location.host&&window.location.host!=""){this.ob=uds2(window.location.host)}else{this.ob=".com"}this.Aa=true;this.Y=udsG(this,GlocalSearch.prototype.ja);this.ya=udsc.yc;this.k="local";this.u="/GlocalSearch";this.g=null;this.W=null}
GlocalSearch.inherits(GSearch);GlocalSearch.RESULT_CLASS="GlocalSearch";GlocalSearch.AD_CLASS="GlocalSearch.ad";GlocalSearch.c=new Array;GlocalSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GlocalSearch.c[udse];GlocalSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GlocalSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GlocalSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GlocalSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){udse=udse+"&q="+encodeURIComponent(uds)}var udsh;if(this.o){var udsk;var udsj;var udso;if(this.ia){udsk=this.o.getCenterLatLng();udsj=this.o.getSpanLatLng();udso=this.o.getZoomLevel();if(udso<0){udso=0}else if(udso>10){udso=10}udsh="&sll="+udsk.y+
","+udsk.x;udsh+="&sspn="+udsj.height+","+udsj.width;udsh+="&z="+udso;udsh+=GlocalSearch.centerToGll(udsk.y,udsk.x);udse+=udsh}else{udsk=this.o.getCenter();udsj=this.o.getBounds().toSpan().toUrlValue();udso=17-this.o.getZoom();if(udso<0){udso=0}else if(udso>10){udso=10}udsh="&sll="+udsk.y+","+udsk.x;udsh+="&sspn="+udsj;udsh+="&z="+udso;udsh+=GlocalSearch.centerToGll(udsk.y,udsk.x);udse+=udsh}}else if(this.w){udsh="&sll="+this.w.y+","+this.w.x;udsh+="&z=6";udsh+=GlocalSearch.centerToGll(this.w.y,this.w.x)
;udse+=udsh}else if(this.A){udsh="&near="+escape(this.A);udse+=udsh}if(this.X){udse+="&nogeocode=t"}return udse}
;GlocalSearch.yd=3.141592653589;GlocalSearch.ld=6367000;GlocalSearch.Hd=16093;GlocalSearch.centerToGll=function(uds,udsa){var udsb=GlocalSearch.Hd;var udsd=2*udsb/GlocalSearch.ld*2*GlocalSearch.yd;var udsf=uds-udsd;var udse=udsa-udsd;var udsh=uds+udsd;var udsk=udsa+udsd;var udsj="&gll="+parseInt(udsf*1000000)+","+parseInt(udse*1000000)+","+parseInt(udsh*1000000)+","+parseInt(udsk*1000000)+"&llsep=500,500";return udsj}
;GlocalSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.url,uds.title,this.d(),udsc.r);udsg(udsa,udsb);var udsd=udsn(udsc.Nb);udsb=udsl(uds.streetAddress,udsc.Vb);udsg(udsd,udsb);var udsf="";if(uds.city!=""){udsf=uds.city;if(uds.region!=""){udsf+=", "}}udsb=udsl(udsf,udsc.Ob);udsg(udsd,udsb);udsb=udsl(uds.region,udsc.Sb);udsg(udsd,udsb);udsb=udsl(uds.country,udsc.Oc);udsg(udsd,udsb);udsg(udsa,udsd);if(uds.phoneNumbers&&
uds.phoneNumbers.length){var udse=null;var udsh=null;var udsk=uds.phoneNumbers[0];var udsj;for(var udso=0;udso<uds.phoneNumbers.length;udso++){udsj=uds.phoneNumbers[udso];if(udsj.type=="main"){udse=udsj;break}if(udsj.type==""||udsj.type=="mobile"&&udsh==null){udsh=udsj}}if(udse){udsj=udse}else if(udsh){udsj=udsh}else{udsj=udsk}udsb=udsl(udsj.number,udsc.Pb);udsg(udsa,udsb)}if(uds.ddUrl&&uds.ddUrl!=""){udsb=udsp(uds.ddUrl,udsi["directions"],this.d(),udsc.Pc);udsg(udsa,udsb)}uds.html=udsa;this.s(uds.html)
}
;GlocalSearch.prototype.fa=function(uds){if(uds.html){delete uds.html}var udsa=udsn(udsc.Rc);udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);if(uds.content1){udsb=udsl(uds.content1,udsc.V);udsg(udsa,udsb)}if(uds.content2){udsb=udsl(uds.content2,udsc.V);udsg(udsa,udsb)}if(uds.phoneNumber){udsb=udsl(uds.phoneNumber,udsc.Pb);udsg(udsa,udsb)}udsb=udsp("#",uds.visibleUrl,null,udsc.E);var udsd=udsB(uds.impressionUrl,12,12,udsc.bb);udsg(udsb,udsd);udsg(udsa,
udsb);if(uds.streetAddress&&uds.city&&uds.region){var udsf=udsn(udsc.Nb);var udse=uds.streetAddress+", ";udsb=udsl(udse,udsc.Vb);udsg(udsf,udsb);udse=uds.city+", ";udsb=udsl(udse,udsc.Ob);udsg(udsf,udsb);udse=uds.region;udsb=udsl(udse,udsc.Sb);udsg(udsf,udsb);udsg(udsa,udsf)}uds.html=udsa;this.s(uds.html)}
;GlocalSearch.prototype.setCenterPoint=function(uds){if(uds.centerAndZoom){this.ia=true;this.o=uds;this.w=null;this.A="";if(this.g){this.g=null}}else if(uds.setCenter){this.ia=false;this.o=uds;this.w=null;this.A="";if(this.g){this.g=null}}else if(uds.x&&uds.y){this.ia=true;this.w=uds;this.o=null;this.A="";if(this.g){this.g=null}}else{if(uds!=null&&uds!=""){this.ia=true;this.o=null;this.A=uds;this.w=null;if(this.g){this.g=null}var udsa=new GlocalSearch;udsa.setSearchCompleteCallback(this,this.cd,[
udsa,uds]);udsa.execute(uds)}}}
;GlocalSearch.prototype.cd=function(uds,udsa){if(uds.results&&uds.results.length){if(window.GMap){var udsb=new GPoint(parseFloat(uds.results[0].lng),parseFloat(uds.results[0].lat));this.w=udsb}else{this.w=null}this.A=udsa;this.Aa=true;this.o=null}}
;GlocalSearch.prototype.ja=function(uds,udsa){if(udsa){if(this.g==null){var udsb=null;if(this.o==null){var udsd=udsn(udsc.Va);this.g=udsR(null,udsc.uc,this.A==""?null:this.A);udsg(udsd,udsl(udsi["search-location"],udsc.tc));udsg(udsd,this.g);udsg(uds,udsd);udsb=this.g}udsd=udsn("gsc-configSetting");this.W=udsL(null,"0",this.X?true:false,udsc.Ua);udsg(udsd,this.W);udsg(udsd,udsl(udsi["disable-address-lookup"],udsc.Ta));if(udsb==null){udsb=this.W}var udsf=udsl(null,"gsc-configSettingSubmit");udsg(udsf,
udsK(udsi["close"],udsc.ca));udsg(udsd,udsf);udsg(uds,udsd);udsb.focus()}}else{if(this.g){if(this.g.value){this.A=this.g.value;this.setCenterPoint(this.A)}this.g=null}if(this.W){if(this.W.checked){this.X=true}else{this.X=false}this.W=null}udsD(uds)}}
;GlocalSearch.ADDRESS_LOOKUP_DISABLED="disabled";GlocalSearch.ADDRESS_LOOKUP_ENABLED="enabled";GlocalSearch.prototype.setAddressLookupMode=function(uds){if(uds==GlocalSearch.ADDRESS_LOOKUP_DISABLED){this.X=true}else if(uds==GlocalSearch.ADDRESS_LOOKUP_ENABLED){this.X=false}}
;
function GblogSearch(){GSearch.call(this);this.k="blog";this.u="/GblogSearch";this.h=null;this.n=false;this.Aa=true;this.Y=udsG(this,GblogSearch.prototype.ja);this.ya="gsc-blogConfig";this.f=null}
GblogSearch.inherits(GSearch);GblogSearch.RESULT_CLASS="GblogSearch";GblogSearch.AD_CLASS="GwebSearch.ad";GblogSearch.c=new Array;GblogSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GblogSearch.c[udse];GblogSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GblogSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GblogSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GblogSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}if(this.h){udsh=udsh+" blogurl:"+this.h}udse=udse+"&q="+encodeURIComponent(udsh);if(this.n){udse=udse+"&scoring=d"}}return udse}
;GblogSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb;udsb=udsp(uds.postUrl,uds.title,this.d(),udsc.r);udsg(udsa,udsb);var udsd=new Date(uds.publishedDate);udsb=udsl(this.Da(udsd),udsc.Qb);udsg(udsa,udsb);udsd=new Date(uds.publishedDate);udsb=udsl(this.cc(udsd),udsc.Tb);udsg(udsa,udsb);udsb=udsl(uds.content,udsc.P);udsg(udsa,udsb);udsb=udsp(uds.blogUrl,uds.blogUrl,this.d(),udsc.E);udsg(udsa,udsb);uds.html=udsa;this.s(uds.html)}
;GblogSearch.prototype.setSiteRestriction=function(uds){if(uds==null||uds==""){this.h=null}else{this.h=uds}}
;GblogSearch.prototype.setResultOrder=function(uds){if(uds==GSearch.ORDER_BY_DATE){this.n=true}else if(uds==GSearch.ORDER_BY_RELEVANCE){this.n=false}else{this.n=false}}
;GblogSearch.prototype.ja=function(uds,udsa){if(udsa){if(this.f==null){var udsb=udsn(udsc.Va);this.f=udsL(null,"0",this.n?true:false,udsc.Ua);udsg(udsb,this.f);udsg(udsb,udsl(udsi["sort-by-date"],udsc.Ta));var udsd=udsn(udsc.ca);udsg(udsd,udsK(udsi["close"],udsc.ca));udsg(udsb,udsd);udsg(uds,udsb);this.f.focus()}else{this.f.checked=this.n?true:false;this.f.focus()}}else{if(this.f){if(this.f.checked){this.setResultOrder(GSearch.ORDER_BY_DATE)}else{this.setResultOrder(GSearch.ORDER_BY_RELEVANCE)}}}
}
;
function GvideoSearch(){GSearch.call(this);this.k="video";this.u="/GvideoSearch"}
GvideoSearch.inherits(GSearch);GvideoSearch.RESULT_CLASS="GvideoSearch";GvideoSearch.AD_CLASS="GwebSearch.ad";GvideoSearch.c=new Array;GvideoSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GvideoSearch.c[udse];GvideoSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GvideoSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GvideoSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GvideoSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}udse=udse+"&q="+encodeURIComponent(udsh)}return udse}
;GvideoSearch.prototype.F=function(uds){if(uds.html){delete uds.html}var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb=udsn(udsc.ea);var udsd=udsn(udsc.wa);var udsf=udsC();var udse=udsy(udsf,0);var udsh=udsr(udse,udsc.ea);var udsk=udsr(udse,udsc.wa);udsg(udsh,udsb);udsg(udsk,udsd);udsg(udsa,udsf);var udsj=GSearch.scaleImage(uds.tbWidth,uds.tbHeight,this.N);var udso=udsB(uds.tbUrl,udsj.width,udsj.height,udsc.D);var udsq=udsM(uds.url,null,this.d(),udsc.D);udsA(udsq,udsc.D);udsg(udsq,udso);udsg(udsb,
udsq);var udsu;udsu=udsp(uds.url,uds.title,this.d(),udsc.r);udsg(udsd,udsu);var udsv=udsl(uds.content,udsc.P);if(udsH()){udsv.style.height="2.6em"}udsg(udsd,udsv);var udsz=new Date(uds.published);udsu=udsl(this.Da(udsz),udsc.Tc);udsg(udsd,udsu);udsu=udsp("http://video.google.com",uds.publisher,this.d(),udsc.Rb);udsg(udsd,udsu);uds.html=udsa;this.s(uds.html)}
;
function GbookSearch(){GSearch.call(this);this.k="book";this.u="/GbookSearch"}
GbookSearch.inherits(GSearch);GbookSearch.RESULT_CLASS="GbookSearch";GbookSearch.AD_CLASS="GwebSearch.ad";GbookSearch.c=new Array;GbookSearch.RawCompletion=function(uds,udsa,udsb,udsd,udsf){var udse=0;if(uds){udse=parseInt(uds)}var udsh=GbookSearch.c[udse];GbookSearch.c[udse]=null;udsh.onSearchComplete(udsa,udsb,udsd,udsf)}
;GbookSearch.prototype.m=function(uds,udsa,udsb){var udsd;if(udsb==null){udsd=GSearch.AllocateCompletionMapContext(GbookSearch.c,this)}else{udsd=udsb}var udsf;if(udsa==null){udsf="GbookSearch.RawCompletion"}else{udsf=udsa}var udse=this.I(udsf,udsd);if(uds){var udsh=uds;if(this.e){udsh=udsh+" "+this.e}udse=udse+"&q="+encodeURIComponent(udsh)}return udse}
;GbookSearch.prototype.F=function(uds){if(uds.html){delete uds.html}uds.thumbnailHtml=this.jd(uds);var udsa=udsn(this.J());udsm(udsa,udsc.q);var udsb=udsn(udsc.wa);var udsd=udsC();var udsf=udsy(udsd,0);var udse=udsr(udsf,udsc.ea);var udsh=udsr(udsf,udsc.wa);udsg(udse,uds.thumbnailHtml.cloneNode(true));udsg(udsh,udsb);udsg(udsa,udsd);var udsk;udsk=udsp(uds.unescapedUrl,uds.title,this.d(),udsc.r);udsg(udsb,udsk);udsk=udsl(uds.authors,udsc.Mc);udsg(udsb,udsk);var udsj=udsl(uds.content,udsc.P);udsg(udsb,
udsj);uds.html=udsa;this.s(uds.html)}
;GbookSearch.prototype.jd=function(uds){var udsa="http://books.google.com/googlebooks/";var udsb=udsn(udsc.ea);var udsd=udsC(0,0,udsc.ea);var udsf=udsy(udsd,0,udsc.Xc);var udse=udsr(udsf,udsc.Ub);var udsh=udsr(udsf,udsc.Vc);var udsk=udsr(udsf,udsc.Uc);var udsj=udsB(udsa+"pages.gif");udsg(udsh,udsj);if(!udsH()){udsj=udsB(udsa+"p_edge.gif");udsg(udsk,udsj)}udsf=udsy(udsd,0,udsc.Yc);udse=udsr(udsf,udsc.Ub);udsh=udsr(udsf,udsc.D);udsj=udsB(udsa+"shadow.gif");udsg(udse,udsj);udsh.setAttribute("colspan"
,2);var udso=GSearch.scaleImage(uds.tbWidth,uds.tbHeight,this.N);udsj=udsB(uds.tbUrl,udso.width,udso.height,udsc.D);var udsq=udsM(uds.unescapedUrl,null,this.d(),udsc.D);udsA(udsq,udsc.D);udsg(udsq,udsj);udsg(udsh,udsq);udsg(udsb,udsd);return udsb}
;
function GsearcherOptions(){this.G=GSearchControl.EXPAND_MODE_PARTIAL;this.ic=this.G;this.root=null;this.N={width:54,height:40};this.ha=true;this.Qa={width:100,height:75}}
GsearcherOptions.prototype.setExpandMode=function(uds){switch(uds){case GSearchControl.EXPAND_MODE_CLOSED:case GSearchControl.EXPAND_MODE_OPEN:case GSearchControl.EXPAND_MODE_PARTIAL:this.G=uds;break;default:this.G=GSearchControl.EXPAND_MODE_PARTIAL;break}this.ic=this.G}
;GsearcherOptions.prototype.setRoot=function(uds){udsD(uds);this.root=uds}
;GsearcherOptions.prototype.setImageResultsTbHeight=function(uds){if(uds>100){uds=100}this.N.height=uds;this.N.width=Math.round(uds*1.33)}
;GsearcherOptions.prototype.setVideoResultsTbHeight=function(uds){if(uds>100){uds=100}this.Qa.height=uds;this.Qa.width=Math.round(uds*1.33)}
;GsearcherOptions.prototype.setImageResultsHorizontal=function(){this.ha=true}
;GsearcherOptions.prototype.setImageResultsVertical=function(){this.ha=false}
;function GdrawOptions(){this.input=null;this.mc=null;this.z=GSearchControl.DRAW_MODE_LINEAR}
GdrawOptions.prototype.setInput=function(uds){this.input=uds}
;GdrawOptions.prototype.setSearchFormRoot=function(uds){this.mc=uds}
;GdrawOptions.prototype.setDrawMode=function(uds){if(uds==GSearchControl.DRAW_MODE_LINEAR||uds==GSearchControl.DRAW_MODE_TABBED){this.z=uds}else{this.z=GSearchControl.DRAW_MODE_LINEAR}}
;function udss(uds,udsa,udsb){this.b=udsb;this.lb=false;this.hb=false;this.gs=uds;this.j=null;this.Cd=udst(udsa,GSearchControl.prototype.xd,[this]);this.Fd=udst(udsa,GSearchControl.prototype.rb,[this,udss.SRC_ONE]);this.Ed=udst(udsa,GSearchControl.prototype.rb,[this,udss.SRC_MORE]);this.Dd=udst(udsa,GSearchControl.prototype.rb,[this,udss.SRC_ALL]);this.Bd=udst(udsa,GSearchControl.prototype.wd,[this]);this.Ad=udst(udsa,GSearchControl.prototype.td,[this]);this.gs.setSearchCompleteCallback(udsa,GSearchControl.prototype.onSearchComplete,
[this]);this.gs.setResultSetSize(udsa.resultSetSize);this.gs.setLinkTarget(udsa.Q);this.root=null;this.Pa=null;this.$=null;this.tb=null;this.L=null;this.Z=null;this.t=null;this.Ea=true}
GSearchControl.TIMEOUT_SHORT=350;GSearchControl.TIMEOUT_MEDIUM=500;GSearchControl.TIMEOUT_LONG=700;GSearchControl.EXPAND_MODE_CLOSED=1;GSearchControl.EXPAND_MODE_OPEN=2;GSearchControl.EXPAND_MODE_PARTIAL=3;GSearchControl.DRAW_MODE_LINEAR=1;GSearchControl.DRAW_MODE_TABBED=2;function GSearchControl(uds){if(!UDS_KeyVerified){if(GSearchControl.keyCheck()){UDS_KeyVerified=true}else{return}}this.resultSetSize=GSearch.SMALL_RESULTSET;this.z=GSearchControl.DRAW_MODE_LINEAR;this.root=null;this.Ka=null;this.input=
null;this.Na=GSearchControl.TIMEOUT_MEDIUM;this.rd=udst(this,GSearchControl.prototype.ud,[null]);this.sd=udst(this,GSearchControl.prototype.vd,[null]);this.ka=null;this.vb=null;this.ub=null;this.aa=null;this.fc=false;this.xa=false;this.Q=GSearch.LINK_TARGET_BLANK;this.Ga=udsi["copy"];this.a=new Array;this.db=new Array;var udsa;if(uds){for(var udsb=0;udsb<uds.length;udsb++){udsa=new udss(uds[udsb],this,false);this.a.push(udsa)}}}
try{GSearchControl.appPath=window.location.href}catch(uds4){GSearchControl.appPath=null}GSearchControl.keyCheck=function(){var uds=true;if(uds3(window.location.host)){return true}if(UDS_LoadFailure){if(UDS_OriginalAppPath&&GSearchControl.appPath){if(GSearchControl.appPath==UDS_OriginalAppPath){alert("AJAX Search API Load Failure: invalid api key supplied");uds=false}else{UDS_LoadFailure=false;uds=true}}}UDS_KeyVerified=true;UDS_LoadFailure=false;return uds}
;GSearchControl.prototype.addSearcher=function(uds,udsa){if(!udsa){udsa=new GsearcherOptions}if(uds.k=="ad"){this.db.push(uds)}else{var udsb=new udss(uds,this,udsa);this.a.push(udsb)}}
;GSearchControl.prototype.draw=function(uds,udsa){var udsb=null;var udsd=null;if(udsa){if(udsa.z){this.z=udsa.z;udsb=udsa.input;udsd=udsa.mc}else{this.z=GSearchControl.DRAW_MODE_LINEAR}}else{this.z=GSearchControl.DRAW_MODE_LINEAR}this.root=udsn(udsc.wc);if(udsb!=null){this.input=udsb;this.input.onkeyup=this.rd;this.input.onpaste=this.sd}else{if(udsd==null){udsd=this.root}var udsf=new GSearchForm(true,udsd);udsf.setOnSubmitCallback(this,GSearchControl.prototype.submit);udsf.setOnClearCallback(this,
GSearchControl.prototype.clearAllResults);this.input=udsf.input}this.la=udsn(udsc.T);if(this.z==GSearchControl.DRAW_MODE_TABBED){this.O=udsn(udsc.Lb);udsg(this.root,this.O);this.i=new Array;this.v=0;for(var udse=0;udse<this.a.length;udse++){var udsh=new Object;udsh.K=udsl(this.a[udse].gs.qd());udsh.M=null;udsh.K.onclick=udst(this,GSearchControl.prototype.Gd,[udse]);this.i[udse]=udsh;udsg(this.O,udsh.K);this.a[udse].b.setExpandMode(GSearchControl.EXPAND_MODE_OPEN)}}udsg(this.root,this.la);for(var udse=
0;udse<this.a.length;udse++){if(this.a[udse].b.root){this.a[udse].Ea=false;this.a[udse].root=this.a[udse].b.root;udsm(this.a[udse].root,udsc.Xa);udsx(this.a[udse].root,udsc.U);udsm(this.a[udse].root,udsc.T)}else{this.a[udse].root=udsn(udsc.Xa)}if(this.a[udse].gs.oa){var udsk=udsc.Xa+"-"+this.a[udse].gs.oa;udsm(this.a[udse].root,udsk)}if(this.z==GSearchControl.DRAW_MODE_TABBED){this.i[udse].M=this.a[udse].root}var udsj=udsC(null,null,udsc.Dc);var udso=udsy(udsj,0);this.a[udse].S=udsr(udso,udsc.Kc)
;var udsq=udsr(udso,udsc.rc);this.a[udse].Pa=udsl("",udsc.Lc);udsg(this.a[udse].S,this.a[udse].Pa);var udsu=udsl(this.a[udse].gs.od(),udsc.Jc);udsg(this.a[udse].Pa,udsu);this.a[udse].$=udsl("",udsc.Gc);udsg(this.a[udse].S,this.a[udse].$);var udsv=udsl();var udsz=udsl(udsi["blank"],udsc.Cc);var udsE=udsl(udsi["blank"],udsc.Bc);var udsF=udsl(udsi["blank"],udsc.Ac);udsz.title=udsi["show-one-result"];udsE.title=udsi["show-more-results"];udsF.title=udsi["show-all-results"];udsg(udsv,udsz);udsg(udsv,udsE)
;udsg(udsv,udsF);udsz.onclick=this.a[udse].Fd;udsE.onclick=this.a[udse].Ed;udsF.onclick=this.a[udse].Dd;this.a[udse].tb=udsv;this.a[udse].wb(udss.SRC_INIT);udsg(this.a[udse].S,this.a[udse].tb);this.a[udse].Pa.onclick=this.a[udse].Cd;if(this.a[udse].gs.Y){this.a[udse].l=udsS("",udsc.sc);udsV(this.a[udse].l,udsi["blank"]);udsm(this.a[udse].l,udsc.da);udsg(udsq,this.a[udse].l);this.a[udse].l.onclick=this.a[udse].Bd;this.a[udse].l.title=udsi["settings"];this.a[udse].L=udsn(udsc.Eb);udsm(this.a[udse].L,
this.a[udse].gs.ya);this.a[udse].Z=udsQ(udsc.Eb);udsm(this.a[udse].Z,this.a[udse].gs.ya);this.a[udse].Z.onsubmit=this.a[udse].Ad;udsg(this.a[udse].L,this.a[udse].Z);this.a[udse].L.style.display="none"}this.a[udse].t=udsn(udsc.Ec);udsm(this.a[udse].t,this.a[udse].gs.nb());if(this.a[udse].b.root==null){udsg(this.la,this.a[udse].root)}udsg(this.a[udse].root,udsj);if(this.a[udse].L){udsg(this.a[udse].root,this.a[udse].L)}udsg(this.a[udse].root,this.a[udse].t)}if(this.z==GSearchControl.DRAW_MODE_TABBED)
{for(var udse=0;udse<this.a.length;udse++){udsm(this.i[udse].K,udsc.Ic);udsm(this.i[udse].M,udsc.Hc);if(udse==this.v){udsm(this.i[udse].K,udsc.$a);udsm(this.i[udse].M,udsc.Ya)}else{udsm(this.i[udse].K,udsc.ab);udsm(this.i[udse].M,udsc.Za)}}}if(uds){udsU(uds,this.root);var udsY=this.nd();if(udsY&&udsY<300){this.fc=true;udsm(this.root,udsc.zc)}}}
;GSearchControl.prototype.setTimeoutInterval=function(uds){switch(uds){case GSearchControl.TIMEOUT_SHORT:case GSearchControl.TIMEOUT_MEDIUM:case GSearchControl.TIMEOUT_LONG:this.Na=uds;break;default:this.Na=GSearchControl.TIMEOUT_MEDIUM;break}}
;GSearchControl.KEEP_LABEL_SAVE="save";GSearchControl.KEEP_LABEL_KEEP="keep";GSearchControl.KEEP_LABEL_INCLUDE="include";GSearchControl.KEEP_LABEL_COPY="copy";GSearchControl.KEEP_LABEL_BLANK="blank";GSearchControl.prototype.setOnKeepCallback=function(uds,udsa,udsb){if(udsb){switch(udsb){case GSearchControl.KEEP_LABEL_SAVE:case GSearchControl.KEEP_LABEL_KEEP:case GSearchControl.KEEP_LABEL_INCLUDE:case GSearchControl.KEEP_LABEL_COPY:case GSearchControl.KEEP_LABEL_BLANK:this.Ga=udsi[udsb];break;default:
this.Ga=udsb;break}}this.ka=udsG(uds,udsa)}
;GSearchControl.prototype.Gd=function(uds){if(this.v==uds){return}udsx(this.i[this.v].K,udsc.$a);udsx(this.i[this.v].M,udsc.Ya);udsm(this.i[this.v].K,udsc.ab);udsm(this.i[this.v].M,udsc.Za);this.v=uds;udsm(this.i[this.v].K,udsc.$a);udsm(this.i[this.v].M,udsc.Ya);udsx(this.i[this.v].K,udsc.ab);udsx(this.i[this.v].M,udsc.Za)}
;GSearchControl.prototype.submit=function(){if(this.input.value.length){this.execute()}else{this.clearAllResults()}return false}
;GSearchControl.prototype.execute=function(uds){var udsa;if(uds){udsa=uds;this.input.value=udsa}else{udsa=this.input.value}if(udsa.length){this.xa=false;udsA(this.la,udsc.U);if(this.O){udsA(this.O,udsc.Mb)}for(var udsb=0;udsb<this.a.length;udsb++){if(!this.a[udsb].Ea){udsx(this.a[udsb].root,udsc.T);udsm(this.a[udsb].root,udsc.U)}if(this.vb){this.vb(this,this.a[udsb].gs,udsa)}this.a[udsb].gs.execute(udsa)}for(var udsb=0;udsb<this.db.length;udsb++){this.db[udsb].execute(udsa)}}}
;GSearchControl.prototype.ud=function(){var uds=this.input.value;if(uds&&uds!=""){if(this.aa){clearTimeout(this.aa)}this.aa=setTimeout(udst(this,GSearchControl.prototype.execute,[null]),this.Na)}}
;GSearchControl.prototype.vd=function(){if(this.aa){clearTimeout(this.aa)}this.aa=setTimeout(udst(this,GSearchControl.prototype.execute,[null]),this.Na)}
;GSearchControl.prototype.setResultSetSize=function(uds){var udsa=true;switch(uds){case GSearch.LARGE_RESULTSET:this.resultSetSize=uds;udsa=true;break;default:case GSearch.SMALL_RESULTSET:this.resultSetSize=GSearch.SMALL_RESULTSET;udsa=false;break}for(var udsb=0;udsb<this.a.length;udsb++){this.a[udsb].gs.setResultSetSize(uds)}}
;GSearchControl.prototype.setLinkTarget=function(uds){this.Q=uds;for(var udsa=0;udsa<this.a.length;udsa++){this.a[udsa].gs.setLinkTarget(uds)}}
;GSearchControl.prototype.xd=function(uds){if(uds.lb){this.R(uds,false)}else{this.R(uds,true)}}
;GSearchControl.prototype.R=function(uds,udsa,udsb){if(!udsa){udsx(uds.S,udsc.va);udsm(uds.S,udsc.da);uds.lb=false;uds.t.style.display="none";if(udsb){var udsd="(0)";uds.$.innerHTML=udsd}else{var udsd="("+(uds.gs.results.length+uds.gs.adResults.length)+")";uds.$.innerHTML=udsd}}else{udsx(uds.S,udsc.da);udsm(uds.S,udsc.va);uds.lb=true;uds.t.style.display="block"}}
;GSearchControl.prototype.td=function(uds){this.ma(uds,false,true);return false}
;GSearchControl.prototype.wd=function(uds){if(uds.gs.Aa){if(uds.hb){this.ma(uds,false,true)}else{this.ma(uds,true,true)}}}
;GSearchControl.prototype.ma=function(uds,udsa,udsb){if(!udsa){if(uds.l){udsx(uds.l,udsc.va);udsm(uds.l,udsc.da);uds.l.innerHTML=udsi["blank"];uds.hb=false;uds.gs.Y(uds.Z,false);uds.L.style.display="none";if(udsb){this.execute()}}}else{if(uds.l){udsm(uds.l,udsc.va);udsx(uds.l,udsc.da);uds.l.innerHTML=udsi["close"];uds.hb=true;uds.L.style.display="block";uds.gs.Y(uds.Z,true)}}}
;GSearchControl.prototype.gc=function(uds,udsa){if(this.ka){udsa.gs.dc();this.ka(uds)}}
;GSearchControl.prototype.cancelSearch=function(){this.xa=true}
;GSearchControl.prototype.clearAllResults=function(){this.input.value="";udsA(this.la,udsc.T);if(this.O){udsA(this.O,udsc.Lb)}for(var uds=0;uds<this.a.length;uds++){if(!this.a[uds].Ea){udsx(this.a[uds].root,udsc.U);udsm(this.a[uds].root,udsc.T)}var udsa=this.a[uds];udsD(udsa.t);udsa.j=null;this.R(udsa,false,true);this.ma(udsa,false,false)}}
;GSearchControl.prototype.onSearchComplete=function(uds){var udsa;var udsb;var udsd=false;var udsf;if(this.xa){return}udsD(uds.t);uds.j=null;this.R(uds,false,true);this.ma(uds,false,false);uds.wb(udss.SRC_INIT);for(var udsb=0;udsb<uds.gs.results.length;udsb++){udsa=uds.gs.results[udsb];if(!udsa.html){uds.gs.F(udsa)}if(udsa.html){udsd=true;udsf=udsn(uds.gs.nb());udsm(udsf,udsc.Wa);if(uds.gs.oa){var udse=udsc.Wa+"-"+uds.gs.oa;udsm(udsf,udse)}var udsh=udsa.html.cloneNode(true);if(udsa.GsearchResultClass==
GimageSearch.RESULT_CLASS){if(uds.b.ha){udsm(udsf,"horizontal")}else{udsm(udsf,"vertical")}if(uds.b.N){var udsk=udsh.getElementsByTagName("img");for(var udsj=0;udsj<udsk.length;udsj++){GSearch.scaleImage(udsa.tbWidth,udsa.tbHeight,uds.b.N,udsk[udsj])}}}else if(udsa.GsearchResultClass==GvideoSearch.RESULT_CLASS){if(uds.b.Qa){var udsk=udsh.getElementsByTagName("img");for(var udsj=0;udsj<udsk.length;udsj++){GSearch.scaleImage(udsa.tbWidth,udsa.tbHeight,uds.b.Qa,udsk[udsj])}}}udsg(udsf,udsh);if(this.ka)
{var udso=this.Ga;if(udsa.GsearchResultClass==GimageSearch.RESULT_CLASS&&uds.b.ha){udso=udsi["blank"]}var udsq=udsl("",udsc.Gb);udsV(udsq,udso);udsg(udsf,udsq);udsq.onclick=udst(this,GSearchControl.prototype.gc,[udsa,uds])}var udsu=uds.gs.hc;if(udsa.GsearchResultClass==GimageSearch.RESULT_CLASS){if(uds.b.ha==false){udsu=1}else{if(this.fc){udsu=2}}}if(udsb>=udsu){if(!uds.j){uds.j=udsn(udsc.xc);udsg(uds.t,uds.j);if(uds.b.G==GSearchControl.EXPAND_MODE_PARTIAL){uds.j.style.display="none"}}udsg(uds.j,
udsf)}else{udsg(uds.t,udsf)}}}var udsv=uds.j?uds.j:uds.t;if(uds.gs.adResults.length){var udsz=udsn(udsc.oc);for(var udsb=0;udsb<uds.gs.adResults.length;udsb++){if(udsb==0){var udsf=udsl(udsi["sponsored-links"],udsc.Qc);udsg(udsz,udsf)}udsa=uds.gs.adResults[udsb];if(!udsa.html){uds.gs.fa(udsa)}if(udsa.html){udsd=true;udsf=udsn(uds.gs.nb());udsm(udsf,udsc.Wa);udsg(udsf,udsa.html.cloneNode(true));if(this.ka){var udsq=udsl(this.Ga,udsc.Gb);udsg(udsf,udsq);udsq.onclick=udst(this,GSearchControl.prototype.gc,
[udsa,uds])}udsg(udsz,udsf)}}udsg(udsv,udsz)}if(!udsd){uds.$.innerHTML="(0)";uds.t.innerHTML="";this.R(uds,false)}else{var udsE;var udsE="("+(uds.gs.results.length+uds.gs.adResults.length)+")";uds.$.innerHTML=udsE;if(uds.b.G==GSearchControl.EXPAND_MODE_PARTIAL||uds.b.G==GSearchControl.EXPAND_MODE_OPEN){this.R(uds,true)}else{this.R(uds,false)}var udsF=uds.gs.getAttribution(true);if(udsF){udsg(uds.t,udsF)}}uds.b.G=uds.b.ic;if(this.ub){this.ub(this,uds.gs)}}
;GSearchControl.Zb={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:
"border-bottom-width",borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:
"overflow",padding:"padding",paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};GSearchControl.inlineCurrentStyle=function(uds,udsa){if(udsZ()){alert("GSearchControl.inlineCurrentStyle is not supported on Safari");return}var udsb=true;if(udsa){udsb=udsa}if(udsb){for(var udsd=0;udsd<
uds.childNodes.length;udsd++){GSearchControl.inlineCurrentStyle(uds.childNodes[udsd],true)}}if(uds.nodeType==1){var udsf;var udse;var udsh=false;var udsk=false;if(window.getComputedStyle){udsf=window.getComputedStyle(uds,null);udse=true;udsh=true}else if(uds.currentStyle){udsf=uds.currentStyle;udse=false;udsh=true}if(udsh){for(var udsj in udsf){if(GSearchControl.Zb[udsj]){var udso=GSearchControl.Zb[udsj];var udsq=udsf[udsj];if(udsj=="display"&&udsq=="none"){uds.innerHTML="";udsk=true}if(udsf[udsj]
!=""){if(udse){uds.style.setProperty(udso,udsq,"")}else{uds.style.setAttribute(udso,udsq,"")}}}}if(udsk){if(udse==false){uds.outerHTML="<div style='display:none'/>"}}}}}
;GSearchControl.prototype.nd=function(uds){var udsa=uds?uds:this.root;var udsb=null;if(window.getComputedStyle){udsb=window.getComputedStyle(udsa,null)}else if(udsa.currentStyle){udsb=udsa.currentStyle}else if(document.defaultView.getComputedStyle){udsb=document.defaultView.getComputedStyle(udsa,null)}if(udsb){return parseInt(udsb["width"])}else{return 300}}
;GSearchControl.prototype.setSearchCompleteCallback=function(uds,udsa){this.ub=udsG(uds,udsa)}
;GSearchControl.prototype.setSearchStartingCallback=function(uds,udsa){this.vb=udsG(uds,udsa)}
;udss.SRC_INIT=0;udss.SRC_ONE=1;udss.SRC_MORE=2;udss.SRC_ALL=3;udss.prototype.wb=function(uds){var udsa=udsc.Fc+" ";if(uds==udss.SRC_INIT){if(this.b.G==GSearchControl.EXPAND_MODE_PARTIAL){udsa+=udsc.Ib}else if(this.gs.getResultSetSize()==GSearch.SMALL_RESULTSET){udsa+=udsc.Hb}else{udsa+=udsc.Bb}}else if(uds==udss.SRC_ONE){udsa+=udsc.Ib}else if(uds==udss.SRC_MORE){udsa+=udsc.Hb}else{udsa+=udsc.Bb}udsA(this.tb,udsa)}
;GSearchControl.prototype.rb=function(uds,udsa){uds.wb(udsa);var udsb=false;switch(udsa){default:case udss.SRC_ONE:if(uds.j){uds.j.style.display="none"}break;case udss.SRC_MORE:if(uds.j){uds.j.style.display="block"}if(uds.gs.getResultSetSize()!=GSearch.SMALL_RESULTSET){udsb=true}uds.gs.setResultSetSize(GSearch.SMALL_RESULTSET);break;case udss.SRC_ALL:if(uds.j){uds.j.style.display="block"}if(uds.gs.getResultSetSize()!=GSearch.LARGE_RESULTSET){udsb=true}uds.gs.setResultSetSize(GSearch.LARGE_RESULTSET)
;break}if(udsb){var udsd;udsd=this.input.value;if(udsd.length){this.xa=false;udsA(this.la,udsc.U);if(this.O){udsA(this.O,udsc.Mb)}if(!uds.Ea){udsx(uds.root,udsc.T);udsm(uds.root,udsc.U)}uds.b.G=GSearchControl.EXPAND_MODE_OPEN;uds.gs.execute(udsd)}}}
;function GSearchForm(uds,udsa){var udsb=udsQ(udsc.Jb);udsb.acceptCharset="utf-8";var udsd=udsi["search-uc"];this.Ka=udsK(udsd,udsc.Kb);this.Ka.title=udsi["search"];var udsf;if(uds){udsf=udsc.pc;this.fb=udsl(udsi["blank"],udsc.Db);this.fb.title=udsi["clear-results"]}else{udsf=udsc.Sa}this.input=udsR(null,udsc.Fb,null);var udse=udsC(null,null,udsc.Jb);udsg(udsb,udse);var udsh=udsy(udse,0);var udsk=udsr(udsh,udsc.Fb);var udsj=udsr(udsh,udsc.Kb);if(uds){var udso=udsr(udsh,udsc.Db);udsg(udso,this.fb)
}udsg(udsk,this.input);udsg(udsj,this.Ka);var udsq=udsC(null,null,udsc.ra);udsg(udsb,udsq);udsh=udsy(udsq,0);this.userDefinedCell=udsr(udsh,udsc.qc);var udsu=udsr(udsh,udsc.ta);var udsv=udsr(udsh,udsf);var udsz=udsl(udsi["powered-by"],udsc.ta);var udsE=UDS_ServiceBase+"/css/small-logo.png";var udsF=udsW(udsE,51,15,udsf);udsg(udsu,udsz);udsg(udsv,udsF);this.ba=udsb;udsD(udsa);udsg(udsa,this.ba)}
GSearchForm.prototype.setOnSubmitCallback=function(uds,udsa){this.Ma=udst(uds,udsa,[this]);this.ba.onsubmit=this.Ma;this.Ka.onclick=this.Ma}
;GSearchForm.prototype.setOnClearCallback=function(uds,udsa){this.fb.onclick=udst(uds,udsa,[this])}
;GSearchForm.prototype.execute=function(uds){if(uds){this.input.value=uds}if(this.Ma){this.Ma()}}
;

